import './style/index.scss';
import { makeInstaller } from './utils';
import components from './list';
export { components };
export * from './components';
export * from './directives';
export * from './hooks';
export * from './utils';
export * from './constants';
export * from './version';
const installer = makeInstaller(components);
export const install = installer.install;
export default install;
