import { createApp } from 'vue';
import { Access } from '@vtj/renderer';
import Designer from './app.vue';
import router from './router';
import './style.scss';
const app = createApp(Designer);
const access = new Access({});
app.use(access);
app.use(router);
app.mount('#app');
